# Generated by Django 5.0 on 2024-01-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_teacher_options_alter_subject_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Название предмета'),
        ),
    ]
